/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical station seed filter stored in stations.seed_features
 */
export interface StationSeed {
  type?: "track" | "artist" | "album" | "cluster" | "mood" | "genre" | "sub_genre" | "uncategorized";
  /**
   * Legacy alias for type; normalized to type on read
   */
  seed_type?: "track" | "artist" | "album" | "cluster" | "mood" | "genre" | "sub_genre" | "uncategorized";
  track_id?: string;
  artist_id?: string;
  album_id?: string;
  cluster_id?: number;
  main_genre?: string;
  sub_genre?: string;
  min_bpm?: number;
  max_bpm?: number;
  min_energy?: number;
  max_energy?: number;
  min_valence?: number;
  max_valence?: number;
}
